### ISSUE TITLE
ユーザーサインアップ、ログインできるところまで

### ISSUE THREAD

**Issue by kk0000-kk** [kk0000-kk/sakura-market#3]
- [x] `devise`インストール
- [x] `User`モデル作成
  - [x] `nick_name:string`追加
- [x] viewカスタマイズできるようにdeviseの設定更新
- [x] views, controllersのカスタマイズ用ファイル生成
- [x] サインアップページ更新
  - [x] `application_controller`で`nick_name`をパラメータとして許可するようにする
  - [x] ニックネームの入力フィールド追加
  - [x] bootstrap当てる
- [x] ログインページ更新
  - [x] bootstrap当てる
- [x] ホームページ更新
  - [x] 未ログイン時、サインアップ/ログイン表示
  - [x] ログイン時、ユーザー情報/ログアウト表示
- [x] Adminはモデル分けて作成

**Comment by kk0000-kk** [comment]
2時間位？

**Comment by ofnhwx** [comment]
> 2時間位？

バラした最小のタスクであればもっと細かく時間を見積もれるのかなーと思いました。
例えば「Userモデル作成」なら5分で終わる、という感じです。

トータルの時間は単にその積み上げなので、もし時間が読めないタスクがあるならさらに
小さくバラす・必要ならスパイクを打つ等して見積もれる状態まで持っていけるとよいですね。

**Comment by kk0000-kk** [comment]
実績2:45（+ペアオペ1時間）くらい
レイアウトをいじっていると時間がかかってしまう。
タスクバラシ時点では、レイアウトの調整にあまり時間かけない予定だったが、イメージしてるのがなかなかできず、時間がかかってしまった。
